language: elixir

sudo: true

cache:
  directories:
    - $HOME/.cargo

install:
  - cargo build --all
  - cargo build --all --release
  - cd sdr-rustler
  - mix local.rebar --force # for Elixir 1.3.0 and up
  - mix local.hex --force
  - mix deps.get

before_install:
  - sudo apt-get install ocl-icd-opencl-dev
  - curl https://sh.rustup.rs -sSf | sh -s -- -y --default-toolchain nightly
  - export PATH=$HOME/.cargo/bin:$PATH
  - rustup update
  - rustc -Vv
  - cargo -V
  - rustup component add rust-src
  - export RUST_SRC_PATH=`rustc --print sysroot`/lib/rustlib/src/rust/src
  - export RUST_BACKTRACE=1

elixir:
  - 1.4.4
otp_release: 19.3

