[package]
name = "math-rustler"
version = "0.1.0"
authors = ["Tomas Korcak <korczis@gmail.com>"]

[[bin]]
name = "math-rustler"
doc = false
path = "src/main.rs"

[dependencies]
rustler = "0.14.0"
rustler_codegen = "0.14.0"
lazy_static = "0.2"
math = { path = "../math-rust"}