[package]
name = "sdr"
version = "0.1.0"
authors = ["Tomas Korcak <korczis@gmail.com>"]

[dependencies]
sdr_hackrf = { path = "../hackrf"}
sdr_rtl = { path = "../rtl"}
sdr_shared = { path = "../sdr-shared"}
