[package]
name = "math-rustler"
version = "0.1.0"
authors = []

[lib]
name = "math_rustler"
path = "src/lib.rs"
crate-type = ["dylib"]

[dependencies]
rustler = "0.15.1"
rustler_codegen = "0.15.1"
lazy_static = "0.2"
math = { path = "../../../math-rust"}
